sudo: required
services:
    - docker

before_install:
    - docker build -t 'tasso85/fibonacci-client:test' -f ./client/Dockerfile.dev ./client

script:
    - docker run 'tasso85/fibonacci-client:test' npm run test-coverage

after_success:
    - docker build -t tasso85/fibonacci-client ./client
    - docker build -t tasso85/fibonacci-server ./server
    - docker build -t tasso85/fibonacci-nginx ./nginx
    - docker build -t tasso85/fibonacci-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push tasso85/fibonacci-client
    - docker push tasso85/fibonacci-server
    - docker push tasso85/fibonacci-nginx
    - docker push tasso85/fibonacci-worker
    - docker logout